server:
  port: 2000

spring:
  application:
    name: panda
  main:
    show_banner: true

logging:
  level:
     org: INFO

eureka:
 client:
   fetchRegistry: true
   registerWithEureka: true
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/

---
spring:
    profiles: test
    main:
      show_banner: false

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
