server:
  port: 8765

spring:
  application:
    name: zuul

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

security:
  sessions: ALWAYS
  ignored: /style/**, /js/**, /views/**, **/favicon.ico

eureka:
  instance:
      metadataMap:
        instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}

zuul:
  ignoredServices: "*"
  routes:
    ui:
      url: /web/**
    panda:
      path: /panda/**

logging:
  level:
    org: INFO
    ROOT: INFO
